#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : design_1.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Nov 03 17:08:29 +0800 2024
# SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved. 
#
# usage: design_1.sh [-help]
# usage: design_1.sh [-lib_map_path]
# usage: design_1.sh [-noclean_files]
# usage: design_1.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'design_1.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_6 zynq_ultra_ps_e_vip_v1_0_6 xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 xbip_pipe_v3_0_6 xbip_dsp48_wrapper_v3_0_4 xbip_dsp48_addsub_v3_0_6 xbip_dsp48_multadd_v3_0_6 xbip_bram18k_v3_0_6 mult_gen_v12_0_16 floating_point_v7_1_9 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 xlconstant_v1_1_6 smartconnect_v1_0 axi_register_slice_v2_1_20 generic_baseblocks_v2_1_0 fifo_generator_v13_2_5 axi_data_fifo_v2_1_19 axi_protocol_converter_v2_1_20 axi_clock_converter_v2_1_19 blk_mem_gen_v8_4_4 axi_dwidth_converter_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "design_1.sh - Script generated by export_simulation (Vivado v2019.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Xilinx/Vivado/2019.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/dc12/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work zynq_ultra_ps_e_vip_v1_0_6 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim/design_1_zynq_ultra_ps_e_0_0_vip_wrapper.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_clk_wiz.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b795/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_multadd_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b0ac/hdl/xbip_dsp48_multadd_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_bram18k_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/d367/hdl/xbip_bram18k_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mult_gen_v12_0_16 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ce84/hdl/mult_gen_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work floating_point_v7_1_9 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/f7b4/hdl/floating_point_v7_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/aligned_bias_scale_m.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/clean_ifm_bank.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/codec_ofm_store_chw_s.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/col_init_cfg.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_Acc_sub.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_Acc_sub_ifxdS.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_Acc_sub_k_wdI.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_Acc_sub_Kx_s.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_Acc_sub_Kyyd2.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calc_s.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calncg.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calocq.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calpcA.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calqcK.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calrcU.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/conv2d_offset_calsc4.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_ama_addmbkb.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_ama_addmjbC.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_b_buf_0_0.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_CTRL_BUS_s_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS0_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS1_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS2_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS3_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS4_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_DATA_BUS5_m_axi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_fadd_32nf26.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_fdiv_32nf47.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_fmul_32nf36.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mul_cud.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaeOg.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaf16.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulag8j.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulagb8.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaGfk.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaHfu.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaIfE.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaJfO.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulakbM.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaKfY.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaLf8.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mac_mulaNgs.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_15nsBew.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_28nstde.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_32s_Aem.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_32s_fYi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_32s_gsb.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_32s_ibs.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_36nsDeQ.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_51nsCeG.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_dEe.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_Ffa.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_ga8.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_gtb.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_hbi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_lbW.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_mb6.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_Mgi.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_udo.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mul_mul_vdy.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mux_42_3Ee0.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_mux_1288f97.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_ofm_buf0gub.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_sitofp_3f57.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_sitofp_3f67.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_udiv_11npwc.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_udiv_16nf77.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_udiv_16nzec.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec_urem_16nf87.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/lc_wrapper.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/lc_wrapper_ifm_buPgM.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/lc_wrapper_ofm_ofOgC.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/ld_ifm_ex.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/load_ifm_k_wrapper.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/load_ifm_pad_square.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/load_kernel_reorg.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_core_w_wraper.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_core_w_wraper_1.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_ifm_rd_wrapper.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_ifm_rd_wrapper_1.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_o_wr_wrappegc8.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_o_wr_wrappegk9.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_o_wr_wrapper.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/mmcpy_o_wr_wrapper_1.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/p_hls_fptosi_float_i.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/post_process.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/row_init_cfg.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/wb_ofm_lb.v" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/verilog/IC_codec.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/ip/IC_codec_ap_fadd_8_full_dsp_32.vhd" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/ip/IC_codec_ap_fdiv_28_no_dsp_32.vhd" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/ip/IC_codec_ap_fmul_4_max_dsp_32.vhd" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/eaee/hdl/ip/IC_codec_ap_sitofp_6_no_dsp_32.vhd" \
    "$ref_dir/../../../bd/design_1/ip/design_1_IC_codec_0_16/sim/design_1_IC_codec_0_16.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_rst_clk_wiz_0_199M_17/sim/design_1_rst_clk_wiz_0_199M_17.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconstant_v1_1_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/34f7/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_0/sim/bd_13ef_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_1/sim/bd_13ef_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/2508/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_2/sim/bd_13ef_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_3/sim/bd_13ef_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/9d43/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_4/sim/bd_13ef_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_5/sim/bd_13ef_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_6/sim/bd_13ef_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_7/sim/bd_13ef_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_8/sim/bd_13ef_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_9/sim/bd_13ef_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_10/sim/bd_13ef_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_11/sim/bd_13ef_m00s2a_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/901a/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/ip/ip_12/sim/bd_13ef_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/bd_0/sim/bd_13ef.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/72d4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_18/sim/design_1_axi_smc_18.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_0/sim/bd_64e8_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_1/sim/bd_64e8_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_2/sim/bd_64e8_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_3/sim/bd_64e8_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_4/sim/bd_64e8_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_5/sim/bd_64e8_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_6/sim/bd_64e8_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_7/sim/bd_64e8_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_8/sim/bd_64e8_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_9/sim/bd_64e8_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_10/sim/bd_64e8_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_11/sim/bd_64e8_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/ip/ip_12/sim/bd_64e8_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/bd_0/sim/bd_64e8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_1_17/sim/design_1_axi_smc_1_17.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_0/sim/bd_21a8_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_1/sim/bd_21a8_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_2/sim/bd_21a8_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_3/sim/bd_21a8_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_4/sim/bd_21a8_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_5/sim/bd_21a8_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_6/sim/bd_21a8_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_7/sim/bd_21a8_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_8/sim/bd_21a8_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_9/sim/bd_21a8_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_10/sim/bd_21a8_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_11/sim/bd_21a8_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_12/sim/bd_21a8_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_13/sim/bd_21a8_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_14/sim/bd_21a8_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_15/sim/bd_21a8_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_16/sim/bd_21a8_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_17/sim/bd_21a8_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_18/sim/bd_21a8_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_19/sim/bd_21a8_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_20/sim/bd_21a8_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_21/sim/bd_21a8_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_22/sim/bd_21a8_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_23/sim/bd_21a8_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_24/sim/bd_21a8_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_25/sim/bd_21a8_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_26/sim/bd_21a8_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_27/sim/bd_21a8_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_28/sim/bd_21a8_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_29/sim/bd_21a8_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_30/sim/bd_21a8_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/ip/ip_31/sim/bd_21a8_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/bd_0/sim/bd_21a8.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_2_14/sim/design_1_axi_smc_2_14.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_0/sim/bd_a818_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_1/sim/bd_a818_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_2/sim/bd_a818_arsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_3/sim/bd_a818_rsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_4/sim/bd_a818_awsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_5/sim/bd_a818_wsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_6/sim/bd_a818_bsw_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_7/sim/bd_a818_s00mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_8/sim/bd_a818_s00tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_9/sim/bd_a818_s00sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_10/sim/bd_a818_s00a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_11/sim/bd_a818_sarn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_12/sim/bd_a818_srn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_13/sim/bd_a818_sawn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_14/sim/bd_a818_swn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_15/sim/bd_a818_sbn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_16/sim/bd_a818_s01mmu_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_17/sim/bd_a818_s01tr_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_18/sim/bd_a818_s01sic_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_19/sim/bd_a818_s01a2s_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_20/sim/bd_a818_sarn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_21/sim/bd_a818_srn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_22/sim/bd_a818_sawn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_23/sim/bd_a818_swn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_24/sim/bd_a818_sbn_1.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_25/sim/bd_a818_m00s2a_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_26/sim/bd_a818_m00arn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_27/sim/bd_a818_m00rn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_28/sim/bd_a818_m00awn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_29/sim/bd_a818_m00wn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_30/sim/bd_a818_m00bn_0.sv" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/ip/ip_31/sim/bd_a818_m00e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/bd_0/sim/bd_a818.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_axi_smc_3_1/sim/design_1_axi_smc_3_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/60de/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/c4a6/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_19 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/9e81/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/d394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/0eaf/hdl" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/4fba" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/1ddd/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ipshared/b2d0/hdl/verilog" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/sim_tlm" +incdir+"$ref_dir/../../../../ic_acc_zcu102_vv1902.srcs/sources_1/bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0" +incdir+"D:/Xilinx/Vivado/2019.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_ds_1/sim/design_1_auto_ds_1.v" \
    "$ref_dir/../../../bd/design_1/ip/design_1_auto_pc_1/sim/design_1_auto_pc_1.v" \
    "$ref_dir/../../../bd/design_1/sim/design_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.design_1 xil_defaultlib.glbl -o design_1_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./design_1_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./design_1.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key design_1_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc design_1_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./design_1.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: design_1.sh [-help]\n\
Usage: design_1.sh [-lib_map_path]\n\
Usage: design_1.sh [-reset_run]\n\
Usage: design_1.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
