-- (c) Copyright 1995-2024 Xilinx, Inc. All rights reserved.
-- 
-- This file contains confidential and proprietary information
-- of Xilinx, Inc. and is protected under U.S. and
-- international copyright and other intellectual property
-- laws.
-- 
-- DISCLAIMER
-- This disclaimer is not a license and does not grant any
-- rights to the materials distributed herewith. Except as
-- otherwise provided in a valid license issued to you by
-- Xilinx, and to the maximum extent permitted by applicable
-- law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
-- WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
-- AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
-- BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
-- INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
-- (2) Xilinx shall not be liable (whether in contract or tort,
-- including negligence, or under any other theory of
-- liability) for any loss or damage of any kind or nature
-- related to, arising under or in connection with these
-- materials, including for any direct, or any indirect,
-- special, incidental, or consequential loss or damage
-- (including loss of data, profits, goodwill, or any type of
-- loss or damage suffered as a result of any action brought
-- by a third party) even if such damage or loss was
-- reasonably foreseeable or Xilinx had been advised of the
-- possibility of the same.
-- 
-- CRITICAL APPLICATIONS
-- Xilinx products are not designed or intended to be fail-
-- safe, or for use in any application requiring fail-safe
-- performance, such as life-support or safety devices or
-- systems, Class III medical devices, nuclear facilities,
-- applications related to the deployment of airbags, or any
-- other applications that could lead to death, personal
-- injury, or severe property or environmental damage
-- (individually and collectively, "Critical
-- Applications"). Customer assumes the sole risk and
-- liability of any use of Xilinx products in Critical
-- Applications, subject only to applicable laws and
-- regulations governing limitations on product liability.
-- 
-- THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
-- PART OF THIS FILE AT ALL TIMES.
-- 
-- DO NOT MODIFY THIS FILE.

-- IP VLNV: xilinx.com:hls:IC_codec:0.0
-- IP Revision: 0

LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

ENTITY design_1_IC_codec_0_16 IS
  PORT (
    s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
    s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
    s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
    s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
    s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
    s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_DATA_BUS0_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS0_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS0_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS0_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS0_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS0_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS0_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS0_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS0_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS0_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS0_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS0_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS0_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS0_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS0_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS0_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS0_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS0_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS0_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS0_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS0_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS0_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS0_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS0_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS0_RREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS1_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS1_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS1_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS1_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS1_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS1_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS1_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS1_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS1_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS1_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS1_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS1_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS1_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS1_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS1_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS1_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS1_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS1_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS1_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS1_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS1_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS1_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS1_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS1_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS1_RREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS4_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS4_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS4_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS4_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS4_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS4_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS4_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS4_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS4_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS4_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS4_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS4_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS4_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS4_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS4_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS4_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS4_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS4_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS4_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS4_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS4_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS4_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS4_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS4_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS4_RREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS5_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS5_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS5_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS5_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS5_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS5_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS5_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS5_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS5_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS5_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS5_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS5_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS5_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS5_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS5_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS5_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS5_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS5_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS5_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS5_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS5_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS5_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS5_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS5_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS5_RREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS2_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS2_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS2_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS2_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS2_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS2_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS2_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS2_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS2_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS2_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS2_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS2_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS2_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS2_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS2_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS2_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS2_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS2_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS2_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS2_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS2_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS2_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS2_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS2_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS2_RREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS3_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS3_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS3_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS3_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS3_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_AWVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS3_AWREADY : IN STD_LOGIC;
    m_axi_DATA_BUS3_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS3_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
    m_axi_DATA_BUS3_WLAST : OUT STD_LOGIC;
    m_axi_DATA_BUS3_WVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS3_WREADY : IN STD_LOGIC;
    m_axi_DATA_BUS3_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_BVALID : IN STD_LOGIC;
    m_axi_DATA_BUS3_BREADY : OUT STD_LOGIC;
    m_axi_DATA_BUS3_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
    m_axi_DATA_BUS3_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
    m_axi_DATA_BUS3_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS3_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
    m_axi_DATA_BUS3_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
    m_axi_DATA_BUS3_ARVALID : OUT STD_LOGIC;
    m_axi_DATA_BUS3_ARREADY : IN STD_LOGIC;
    m_axi_DATA_BUS3_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
    m_axi_DATA_BUS3_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
    m_axi_DATA_BUS3_RLAST : IN STD_LOGIC;
    m_axi_DATA_BUS3_RVALID : IN STD_LOGIC;
    m_axi_DATA_BUS3_RREADY : OUT STD_LOGIC
  );
END design_1_IC_codec_0_16;

ARCHITECTURE design_1_IC_codec_0_16_arch OF design_1_IC_codec_0_16 IS
  ATTRIBUTE DowngradeIPIdentifiedWarnings : STRING;
  ATTRIBUTE DowngradeIPIdentifiedWarnings OF design_1_IC_codec_0_16_arch: ARCHITECTURE IS "yes";
  COMPONENT IC_codec IS
    GENERIC (
      C_S_AXI_CTRL_BUS_ADDR_WIDTH : INTEGER;
      C_S_AXI_CTRL_BUS_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS0_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS0_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS0_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_BUS1_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS1_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS1_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS1_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_BUS4_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS4_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS4_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS4_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_BUS5_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS5_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS5_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS5_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_BUS2_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS2_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS2_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS2_CACHE_VALUE : INTEGER;
      C_M_AXI_DATA_BUS3_ID_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_ADDR_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_DATA_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_AWUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_ARUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_WUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_RUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_BUSER_WIDTH : INTEGER;
      C_M_AXI_DATA_BUS3_USER_VALUE : INTEGER;
      C_M_AXI_DATA_BUS3_PROT_VALUE : INTEGER;
      C_M_AXI_DATA_BUS3_CACHE_VALUE : INTEGER
    );
    PORT (
      s_axi_CTRL_BUS_AWADDR : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
      s_axi_CTRL_BUS_AWVALID : IN STD_LOGIC;
      s_axi_CTRL_BUS_AWREADY : OUT STD_LOGIC;
      s_axi_CTRL_BUS_WDATA : IN STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTRL_BUS_WSTRB : IN STD_LOGIC_VECTOR(3 DOWNTO 0);
      s_axi_CTRL_BUS_WVALID : IN STD_LOGIC;
      s_axi_CTRL_BUS_WREADY : OUT STD_LOGIC;
      s_axi_CTRL_BUS_BRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTRL_BUS_BVALID : OUT STD_LOGIC;
      s_axi_CTRL_BUS_BREADY : IN STD_LOGIC;
      s_axi_CTRL_BUS_ARADDR : IN STD_LOGIC_VECTOR(8 DOWNTO 0);
      s_axi_CTRL_BUS_ARVALID : IN STD_LOGIC;
      s_axi_CTRL_BUS_ARREADY : OUT STD_LOGIC;
      s_axi_CTRL_BUS_RDATA : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      s_axi_CTRL_BUS_RRESP : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      s_axi_CTRL_BUS_RVALID : OUT STD_LOGIC;
      s_axi_CTRL_BUS_RREADY : IN STD_LOGIC;
      ap_clk : IN STD_LOGIC;
      ap_rst_n : IN STD_LOGIC;
      interrupt : OUT STD_LOGIC;
      m_axi_DATA_BUS0_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS0_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS0_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS0_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS0_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS0_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS0_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS0_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS0_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS0_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS0_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS0_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS0_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS0_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS0_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS0_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS0_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS0_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS0_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS0_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS0_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS0_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS0_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS0_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS0_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS0_RREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS1_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS1_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS1_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS1_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS1_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS1_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS1_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS1_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS1_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS1_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS1_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS1_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS1_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS1_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS1_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS1_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS1_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS1_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS1_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS1_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS1_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS1_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS1_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS1_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS1_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS1_RREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS4_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS4_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS4_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS4_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS4_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS4_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS4_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS4_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS4_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS4_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS4_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS4_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS4_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS4_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS4_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS4_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS4_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS4_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS4_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS4_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS4_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS4_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS4_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS4_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS4_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS4_RREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS5_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS5_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS5_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS5_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS5_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS5_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS5_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS5_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS5_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS5_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS5_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS5_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS5_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS5_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS5_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS5_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS5_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS5_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS5_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS5_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS5_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS5_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS5_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS5_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS5_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS5_RREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS2_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS2_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS2_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS2_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS2_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS2_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS2_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS2_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS2_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS2_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS2_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS2_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS2_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS2_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS2_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS2_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS2_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS2_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS2_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS2_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS2_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS2_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS2_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS2_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS2_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS2_RREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS3_AWID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_AWADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS3_AWLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS3_AWSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS3_AWBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_AWLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_AWREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_AWCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_AWPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS3_AWQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_AWUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_AWVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS3_AWREADY : IN STD_LOGIC;
      m_axi_DATA_BUS3_WID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_WDATA : OUT STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS3_WSTRB : OUT STD_LOGIC_VECTOR(15 DOWNTO 0);
      m_axi_DATA_BUS3_WLAST : OUT STD_LOGIC;
      m_axi_DATA_BUS3_WUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_WVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS3_WREADY : IN STD_LOGIC;
      m_axi_DATA_BUS3_BID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_BRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_BUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_BVALID : IN STD_LOGIC;
      m_axi_DATA_BUS3_BREADY : OUT STD_LOGIC;
      m_axi_DATA_BUS3_ARID : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_ARADDR : OUT STD_LOGIC_VECTOR(31 DOWNTO 0);
      m_axi_DATA_BUS3_ARLEN : OUT STD_LOGIC_VECTOR(7 DOWNTO 0);
      m_axi_DATA_BUS3_ARSIZE : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS3_ARBURST : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_ARLOCK : OUT STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_ARREGION : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_ARCACHE : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_ARPROT : OUT STD_LOGIC_VECTOR(2 DOWNTO 0);
      m_axi_DATA_BUS3_ARQOS : OUT STD_LOGIC_VECTOR(3 DOWNTO 0);
      m_axi_DATA_BUS3_ARUSER : OUT STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_ARVALID : OUT STD_LOGIC;
      m_axi_DATA_BUS3_ARREADY : IN STD_LOGIC;
      m_axi_DATA_BUS3_RID : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_RDATA : IN STD_LOGIC_VECTOR(127 DOWNTO 0);
      m_axi_DATA_BUS3_RRESP : IN STD_LOGIC_VECTOR(1 DOWNTO 0);
      m_axi_DATA_BUS3_RLAST : IN STD_LOGIC;
      m_axi_DATA_BUS3_RUSER : IN STD_LOGIC_VECTOR(0 DOWNTO 0);
      m_axi_DATA_BUS3_RVALID : IN STD_LOGIC;
      m_axi_DATA_BUS3_RREADY : OUT STD_LOGIC
    );
  END COMPONENT IC_codec;
  ATTRIBUTE IP_DEFINITION_SOURCE : STRING;
  ATTRIBUTE IP_DEFINITION_SOURCE OF design_1_IC_codec_0_16_arch: ARCHITECTURE IS "HLS";
  ATTRIBUTE X_INTERFACE_INFO : STRING;
  ATTRIBUTE X_INTERFACE_PARAMETER : STRING;
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS3_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS3, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS3_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS3 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS2_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS2, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS2_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS2 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS5_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS5, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS5_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS5 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS4_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS4, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS4_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS4 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS1_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS1, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS1_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS1 AWADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_RLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 RLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARLEN";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_WLAST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 WLAST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWVALID";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWQOS: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWQOS";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWPROT: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWPROT";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWCACHE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWCACHE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWREGION: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWREGION";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWLOCK: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWLOCK";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWBURST: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWBURST";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWSIZE: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWSIZE";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWLEN: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWLEN";
  ATTRIBUTE X_INTERFACE_PARAMETER OF m_axi_DATA_BUS0_AWADDR: SIGNAL IS "XIL_INTERFACENAME m_axi_DATA_BUS0, ADDR_WIDTH 32, MAX_BURST_LENGTH 256, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_READ_BURST_LENGTH 256, MAX_WRITE_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_WRITE, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, DATA_WIDTH 128, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOM" & 
"AIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF m_axi_DATA_BUS0_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 m_axi_DATA_BUS0 AWADDR";
  ATTRIBUTE X_INTERFACE_PARAMETER OF interrupt: SIGNAL IS "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  ATTRIBUTE X_INTERFACE_INFO OF interrupt: SIGNAL IS "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_rst_n: SIGNAL IS "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_rst_n: SIGNAL IS "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  ATTRIBUTE X_INTERFACE_PARAMETER OF ap_clk: SIGNAL IS "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_CTRL_BUS:m_axi_DATA_BUS0:m_axi_DATA_BUS1:m_axi_DATA_BUS4:m_axi_DATA_BUS5:m_axi_DATA_BUS2:m_axi_DATA_BUS3, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 199998562, PHASE 0.0, CLK_DOMAIN design_1_clk_wiz_0_0_clk_out1, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF ap_clk: SIGNAL IS "xilinx.com:signal:clock:1.0 ap_clk CLK";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_RREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS RREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_RVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS RVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_RRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS RRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_RDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS RDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_ARREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS ARREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_ARVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS ARVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_ARADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS ARADDR";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_BREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS BREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_BVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS BVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_BRESP: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS BRESP";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_WREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS WREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_WVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS WVALID";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_WSTRB: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS WSTRB";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_WDATA: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS WDATA";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_AWREADY: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS AWREADY";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_AWVALID: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS AWVALID";
  ATTRIBUTE X_INTERFACE_PARAMETER OF s_axi_CTRL_BUS_AWADDR: SIGNAL IS "XIL_INTERFACENAME s_axi_CTRL_BUS, ADDR_WIDTH 9, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 199998562, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN design_1_clk_wiz_0_0_clk_out1, NUM_READ_THREADS 4, N" & 
"UM_WRITE_THREADS 4, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  ATTRIBUTE X_INTERFACE_INFO OF s_axi_CTRL_BUS_AWADDR: SIGNAL IS "xilinx.com:interface:aximm:1.0 s_axi_CTRL_BUS AWADDR";
BEGIN
  U0 : IC_codec
    GENERIC MAP (
      C_S_AXI_CTRL_BUS_ADDR_WIDTH => 9,
      C_S_AXI_CTRL_BUS_DATA_WIDTH => 32,
      C_M_AXI_DATA_BUS0_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS0_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS0_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS0_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS0_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS0_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS0_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS0_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS0_USER_VALUE => 0,
      C_M_AXI_DATA_BUS0_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS0_CACHE_VALUE => 3,
      C_M_AXI_DATA_BUS1_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS1_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS1_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS1_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS1_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS1_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS1_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS1_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS1_USER_VALUE => 0,
      C_M_AXI_DATA_BUS1_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS1_CACHE_VALUE => 3,
      C_M_AXI_DATA_BUS4_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS4_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS4_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS4_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS4_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS4_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS4_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS4_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS4_USER_VALUE => 0,
      C_M_AXI_DATA_BUS4_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS4_CACHE_VALUE => 3,
      C_M_AXI_DATA_BUS5_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS5_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS5_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS5_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS5_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS5_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS5_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS5_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS5_USER_VALUE => 0,
      C_M_AXI_DATA_BUS5_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS5_CACHE_VALUE => 3,
      C_M_AXI_DATA_BUS2_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS2_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS2_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS2_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS2_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS2_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS2_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS2_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS2_USER_VALUE => 0,
      C_M_AXI_DATA_BUS2_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS2_CACHE_VALUE => 3,
      C_M_AXI_DATA_BUS3_ID_WIDTH => 1,
      C_M_AXI_DATA_BUS3_ADDR_WIDTH => 32,
      C_M_AXI_DATA_BUS3_DATA_WIDTH => 128,
      C_M_AXI_DATA_BUS3_AWUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS3_ARUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS3_WUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS3_RUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS3_BUSER_WIDTH => 1,
      C_M_AXI_DATA_BUS3_USER_VALUE => 0,
      C_M_AXI_DATA_BUS3_PROT_VALUE => 0,
      C_M_AXI_DATA_BUS3_CACHE_VALUE => 3
    )
    PORT MAP (
      s_axi_CTRL_BUS_AWADDR => s_axi_CTRL_BUS_AWADDR,
      s_axi_CTRL_BUS_AWVALID => s_axi_CTRL_BUS_AWVALID,
      s_axi_CTRL_BUS_AWREADY => s_axi_CTRL_BUS_AWREADY,
      s_axi_CTRL_BUS_WDATA => s_axi_CTRL_BUS_WDATA,
      s_axi_CTRL_BUS_WSTRB => s_axi_CTRL_BUS_WSTRB,
      s_axi_CTRL_BUS_WVALID => s_axi_CTRL_BUS_WVALID,
      s_axi_CTRL_BUS_WREADY => s_axi_CTRL_BUS_WREADY,
      s_axi_CTRL_BUS_BRESP => s_axi_CTRL_BUS_BRESP,
      s_axi_CTRL_BUS_BVALID => s_axi_CTRL_BUS_BVALID,
      s_axi_CTRL_BUS_BREADY => s_axi_CTRL_BUS_BREADY,
      s_axi_CTRL_BUS_ARADDR => s_axi_CTRL_BUS_ARADDR,
      s_axi_CTRL_BUS_ARVALID => s_axi_CTRL_BUS_ARVALID,
      s_axi_CTRL_BUS_ARREADY => s_axi_CTRL_BUS_ARREADY,
      s_axi_CTRL_BUS_RDATA => s_axi_CTRL_BUS_RDATA,
      s_axi_CTRL_BUS_RRESP => s_axi_CTRL_BUS_RRESP,
      s_axi_CTRL_BUS_RVALID => s_axi_CTRL_BUS_RVALID,
      s_axi_CTRL_BUS_RREADY => s_axi_CTRL_BUS_RREADY,
      ap_clk => ap_clk,
      ap_rst_n => ap_rst_n,
      interrupt => interrupt,
      m_axi_DATA_BUS0_AWADDR => m_axi_DATA_BUS0_AWADDR,
      m_axi_DATA_BUS0_AWLEN => m_axi_DATA_BUS0_AWLEN,
      m_axi_DATA_BUS0_AWSIZE => m_axi_DATA_BUS0_AWSIZE,
      m_axi_DATA_BUS0_AWBURST => m_axi_DATA_BUS0_AWBURST,
      m_axi_DATA_BUS0_AWLOCK => m_axi_DATA_BUS0_AWLOCK,
      m_axi_DATA_BUS0_AWREGION => m_axi_DATA_BUS0_AWREGION,
      m_axi_DATA_BUS0_AWCACHE => m_axi_DATA_BUS0_AWCACHE,
      m_axi_DATA_BUS0_AWPROT => m_axi_DATA_BUS0_AWPROT,
      m_axi_DATA_BUS0_AWQOS => m_axi_DATA_BUS0_AWQOS,
      m_axi_DATA_BUS0_AWVALID => m_axi_DATA_BUS0_AWVALID,
      m_axi_DATA_BUS0_AWREADY => m_axi_DATA_BUS0_AWREADY,
      m_axi_DATA_BUS0_WDATA => m_axi_DATA_BUS0_WDATA,
      m_axi_DATA_BUS0_WSTRB => m_axi_DATA_BUS0_WSTRB,
      m_axi_DATA_BUS0_WLAST => m_axi_DATA_BUS0_WLAST,
      m_axi_DATA_BUS0_WVALID => m_axi_DATA_BUS0_WVALID,
      m_axi_DATA_BUS0_WREADY => m_axi_DATA_BUS0_WREADY,
      m_axi_DATA_BUS0_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS0_BRESP => m_axi_DATA_BUS0_BRESP,
      m_axi_DATA_BUS0_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS0_BVALID => m_axi_DATA_BUS0_BVALID,
      m_axi_DATA_BUS0_BREADY => m_axi_DATA_BUS0_BREADY,
      m_axi_DATA_BUS0_ARADDR => m_axi_DATA_BUS0_ARADDR,
      m_axi_DATA_BUS0_ARLEN => m_axi_DATA_BUS0_ARLEN,
      m_axi_DATA_BUS0_ARSIZE => m_axi_DATA_BUS0_ARSIZE,
      m_axi_DATA_BUS0_ARBURST => m_axi_DATA_BUS0_ARBURST,
      m_axi_DATA_BUS0_ARLOCK => m_axi_DATA_BUS0_ARLOCK,
      m_axi_DATA_BUS0_ARREGION => m_axi_DATA_BUS0_ARREGION,
      m_axi_DATA_BUS0_ARCACHE => m_axi_DATA_BUS0_ARCACHE,
      m_axi_DATA_BUS0_ARPROT => m_axi_DATA_BUS0_ARPROT,
      m_axi_DATA_BUS0_ARQOS => m_axi_DATA_BUS0_ARQOS,
      m_axi_DATA_BUS0_ARVALID => m_axi_DATA_BUS0_ARVALID,
      m_axi_DATA_BUS0_ARREADY => m_axi_DATA_BUS0_ARREADY,
      m_axi_DATA_BUS0_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS0_RDATA => m_axi_DATA_BUS0_RDATA,
      m_axi_DATA_BUS0_RRESP => m_axi_DATA_BUS0_RRESP,
      m_axi_DATA_BUS0_RLAST => m_axi_DATA_BUS0_RLAST,
      m_axi_DATA_BUS0_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS0_RVALID => m_axi_DATA_BUS0_RVALID,
      m_axi_DATA_BUS0_RREADY => m_axi_DATA_BUS0_RREADY,
      m_axi_DATA_BUS1_AWADDR => m_axi_DATA_BUS1_AWADDR,
      m_axi_DATA_BUS1_AWLEN => m_axi_DATA_BUS1_AWLEN,
      m_axi_DATA_BUS1_AWSIZE => m_axi_DATA_BUS1_AWSIZE,
      m_axi_DATA_BUS1_AWBURST => m_axi_DATA_BUS1_AWBURST,
      m_axi_DATA_BUS1_AWLOCK => m_axi_DATA_BUS1_AWLOCK,
      m_axi_DATA_BUS1_AWREGION => m_axi_DATA_BUS1_AWREGION,
      m_axi_DATA_BUS1_AWCACHE => m_axi_DATA_BUS1_AWCACHE,
      m_axi_DATA_BUS1_AWPROT => m_axi_DATA_BUS1_AWPROT,
      m_axi_DATA_BUS1_AWQOS => m_axi_DATA_BUS1_AWQOS,
      m_axi_DATA_BUS1_AWVALID => m_axi_DATA_BUS1_AWVALID,
      m_axi_DATA_BUS1_AWREADY => m_axi_DATA_BUS1_AWREADY,
      m_axi_DATA_BUS1_WDATA => m_axi_DATA_BUS1_WDATA,
      m_axi_DATA_BUS1_WSTRB => m_axi_DATA_BUS1_WSTRB,
      m_axi_DATA_BUS1_WLAST => m_axi_DATA_BUS1_WLAST,
      m_axi_DATA_BUS1_WVALID => m_axi_DATA_BUS1_WVALID,
      m_axi_DATA_BUS1_WREADY => m_axi_DATA_BUS1_WREADY,
      m_axi_DATA_BUS1_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS1_BRESP => m_axi_DATA_BUS1_BRESP,
      m_axi_DATA_BUS1_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS1_BVALID => m_axi_DATA_BUS1_BVALID,
      m_axi_DATA_BUS1_BREADY => m_axi_DATA_BUS1_BREADY,
      m_axi_DATA_BUS1_ARADDR => m_axi_DATA_BUS1_ARADDR,
      m_axi_DATA_BUS1_ARLEN => m_axi_DATA_BUS1_ARLEN,
      m_axi_DATA_BUS1_ARSIZE => m_axi_DATA_BUS1_ARSIZE,
      m_axi_DATA_BUS1_ARBURST => m_axi_DATA_BUS1_ARBURST,
      m_axi_DATA_BUS1_ARLOCK => m_axi_DATA_BUS1_ARLOCK,
      m_axi_DATA_BUS1_ARREGION => m_axi_DATA_BUS1_ARREGION,
      m_axi_DATA_BUS1_ARCACHE => m_axi_DATA_BUS1_ARCACHE,
      m_axi_DATA_BUS1_ARPROT => m_axi_DATA_BUS1_ARPROT,
      m_axi_DATA_BUS1_ARQOS => m_axi_DATA_BUS1_ARQOS,
      m_axi_DATA_BUS1_ARVALID => m_axi_DATA_BUS1_ARVALID,
      m_axi_DATA_BUS1_ARREADY => m_axi_DATA_BUS1_ARREADY,
      m_axi_DATA_BUS1_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS1_RDATA => m_axi_DATA_BUS1_RDATA,
      m_axi_DATA_BUS1_RRESP => m_axi_DATA_BUS1_RRESP,
      m_axi_DATA_BUS1_RLAST => m_axi_DATA_BUS1_RLAST,
      m_axi_DATA_BUS1_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS1_RVALID => m_axi_DATA_BUS1_RVALID,
      m_axi_DATA_BUS1_RREADY => m_axi_DATA_BUS1_RREADY,
      m_axi_DATA_BUS4_AWADDR => m_axi_DATA_BUS4_AWADDR,
      m_axi_DATA_BUS4_AWLEN => m_axi_DATA_BUS4_AWLEN,
      m_axi_DATA_BUS4_AWSIZE => m_axi_DATA_BUS4_AWSIZE,
      m_axi_DATA_BUS4_AWBURST => m_axi_DATA_BUS4_AWBURST,
      m_axi_DATA_BUS4_AWLOCK => m_axi_DATA_BUS4_AWLOCK,
      m_axi_DATA_BUS4_AWREGION => m_axi_DATA_BUS4_AWREGION,
      m_axi_DATA_BUS4_AWCACHE => m_axi_DATA_BUS4_AWCACHE,
      m_axi_DATA_BUS4_AWPROT => m_axi_DATA_BUS4_AWPROT,
      m_axi_DATA_BUS4_AWQOS => m_axi_DATA_BUS4_AWQOS,
      m_axi_DATA_BUS4_AWVALID => m_axi_DATA_BUS4_AWVALID,
      m_axi_DATA_BUS4_AWREADY => m_axi_DATA_BUS4_AWREADY,
      m_axi_DATA_BUS4_WDATA => m_axi_DATA_BUS4_WDATA,
      m_axi_DATA_BUS4_WSTRB => m_axi_DATA_BUS4_WSTRB,
      m_axi_DATA_BUS4_WLAST => m_axi_DATA_BUS4_WLAST,
      m_axi_DATA_BUS4_WVALID => m_axi_DATA_BUS4_WVALID,
      m_axi_DATA_BUS4_WREADY => m_axi_DATA_BUS4_WREADY,
      m_axi_DATA_BUS4_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS4_BRESP => m_axi_DATA_BUS4_BRESP,
      m_axi_DATA_BUS4_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS4_BVALID => m_axi_DATA_BUS4_BVALID,
      m_axi_DATA_BUS4_BREADY => m_axi_DATA_BUS4_BREADY,
      m_axi_DATA_BUS4_ARADDR => m_axi_DATA_BUS4_ARADDR,
      m_axi_DATA_BUS4_ARLEN => m_axi_DATA_BUS4_ARLEN,
      m_axi_DATA_BUS4_ARSIZE => m_axi_DATA_BUS4_ARSIZE,
      m_axi_DATA_BUS4_ARBURST => m_axi_DATA_BUS4_ARBURST,
      m_axi_DATA_BUS4_ARLOCK => m_axi_DATA_BUS4_ARLOCK,
      m_axi_DATA_BUS4_ARREGION => m_axi_DATA_BUS4_ARREGION,
      m_axi_DATA_BUS4_ARCACHE => m_axi_DATA_BUS4_ARCACHE,
      m_axi_DATA_BUS4_ARPROT => m_axi_DATA_BUS4_ARPROT,
      m_axi_DATA_BUS4_ARQOS => m_axi_DATA_BUS4_ARQOS,
      m_axi_DATA_BUS4_ARVALID => m_axi_DATA_BUS4_ARVALID,
      m_axi_DATA_BUS4_ARREADY => m_axi_DATA_BUS4_ARREADY,
      m_axi_DATA_BUS4_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS4_RDATA => m_axi_DATA_BUS4_RDATA,
      m_axi_DATA_BUS4_RRESP => m_axi_DATA_BUS4_RRESP,
      m_axi_DATA_BUS4_RLAST => m_axi_DATA_BUS4_RLAST,
      m_axi_DATA_BUS4_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS4_RVALID => m_axi_DATA_BUS4_RVALID,
      m_axi_DATA_BUS4_RREADY => m_axi_DATA_BUS4_RREADY,
      m_axi_DATA_BUS5_AWADDR => m_axi_DATA_BUS5_AWADDR,
      m_axi_DATA_BUS5_AWLEN => m_axi_DATA_BUS5_AWLEN,
      m_axi_DATA_BUS5_AWSIZE => m_axi_DATA_BUS5_AWSIZE,
      m_axi_DATA_BUS5_AWBURST => m_axi_DATA_BUS5_AWBURST,
      m_axi_DATA_BUS5_AWLOCK => m_axi_DATA_BUS5_AWLOCK,
      m_axi_DATA_BUS5_AWREGION => m_axi_DATA_BUS5_AWREGION,
      m_axi_DATA_BUS5_AWCACHE => m_axi_DATA_BUS5_AWCACHE,
      m_axi_DATA_BUS5_AWPROT => m_axi_DATA_BUS5_AWPROT,
      m_axi_DATA_BUS5_AWQOS => m_axi_DATA_BUS5_AWQOS,
      m_axi_DATA_BUS5_AWVALID => m_axi_DATA_BUS5_AWVALID,
      m_axi_DATA_BUS5_AWREADY => m_axi_DATA_BUS5_AWREADY,
      m_axi_DATA_BUS5_WDATA => m_axi_DATA_BUS5_WDATA,
      m_axi_DATA_BUS5_WSTRB => m_axi_DATA_BUS5_WSTRB,
      m_axi_DATA_BUS5_WLAST => m_axi_DATA_BUS5_WLAST,
      m_axi_DATA_BUS5_WVALID => m_axi_DATA_BUS5_WVALID,
      m_axi_DATA_BUS5_WREADY => m_axi_DATA_BUS5_WREADY,
      m_axi_DATA_BUS5_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS5_BRESP => m_axi_DATA_BUS5_BRESP,
      m_axi_DATA_BUS5_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS5_BVALID => m_axi_DATA_BUS5_BVALID,
      m_axi_DATA_BUS5_BREADY => m_axi_DATA_BUS5_BREADY,
      m_axi_DATA_BUS5_ARADDR => m_axi_DATA_BUS5_ARADDR,
      m_axi_DATA_BUS5_ARLEN => m_axi_DATA_BUS5_ARLEN,
      m_axi_DATA_BUS5_ARSIZE => m_axi_DATA_BUS5_ARSIZE,
      m_axi_DATA_BUS5_ARBURST => m_axi_DATA_BUS5_ARBURST,
      m_axi_DATA_BUS5_ARLOCK => m_axi_DATA_BUS5_ARLOCK,
      m_axi_DATA_BUS5_ARREGION => m_axi_DATA_BUS5_ARREGION,
      m_axi_DATA_BUS5_ARCACHE => m_axi_DATA_BUS5_ARCACHE,
      m_axi_DATA_BUS5_ARPROT => m_axi_DATA_BUS5_ARPROT,
      m_axi_DATA_BUS5_ARQOS => m_axi_DATA_BUS5_ARQOS,
      m_axi_DATA_BUS5_ARVALID => m_axi_DATA_BUS5_ARVALID,
      m_axi_DATA_BUS5_ARREADY => m_axi_DATA_BUS5_ARREADY,
      m_axi_DATA_BUS5_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS5_RDATA => m_axi_DATA_BUS5_RDATA,
      m_axi_DATA_BUS5_RRESP => m_axi_DATA_BUS5_RRESP,
      m_axi_DATA_BUS5_RLAST => m_axi_DATA_BUS5_RLAST,
      m_axi_DATA_BUS5_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS5_RVALID => m_axi_DATA_BUS5_RVALID,
      m_axi_DATA_BUS5_RREADY => m_axi_DATA_BUS5_RREADY,
      m_axi_DATA_BUS2_AWADDR => m_axi_DATA_BUS2_AWADDR,
      m_axi_DATA_BUS2_AWLEN => m_axi_DATA_BUS2_AWLEN,
      m_axi_DATA_BUS2_AWSIZE => m_axi_DATA_BUS2_AWSIZE,
      m_axi_DATA_BUS2_AWBURST => m_axi_DATA_BUS2_AWBURST,
      m_axi_DATA_BUS2_AWLOCK => m_axi_DATA_BUS2_AWLOCK,
      m_axi_DATA_BUS2_AWREGION => m_axi_DATA_BUS2_AWREGION,
      m_axi_DATA_BUS2_AWCACHE => m_axi_DATA_BUS2_AWCACHE,
      m_axi_DATA_BUS2_AWPROT => m_axi_DATA_BUS2_AWPROT,
      m_axi_DATA_BUS2_AWQOS => m_axi_DATA_BUS2_AWQOS,
      m_axi_DATA_BUS2_AWVALID => m_axi_DATA_BUS2_AWVALID,
      m_axi_DATA_BUS2_AWREADY => m_axi_DATA_BUS2_AWREADY,
      m_axi_DATA_BUS2_WDATA => m_axi_DATA_BUS2_WDATA,
      m_axi_DATA_BUS2_WSTRB => m_axi_DATA_BUS2_WSTRB,
      m_axi_DATA_BUS2_WLAST => m_axi_DATA_BUS2_WLAST,
      m_axi_DATA_BUS2_WVALID => m_axi_DATA_BUS2_WVALID,
      m_axi_DATA_BUS2_WREADY => m_axi_DATA_BUS2_WREADY,
      m_axi_DATA_BUS2_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS2_BRESP => m_axi_DATA_BUS2_BRESP,
      m_axi_DATA_BUS2_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS2_BVALID => m_axi_DATA_BUS2_BVALID,
      m_axi_DATA_BUS2_BREADY => m_axi_DATA_BUS2_BREADY,
      m_axi_DATA_BUS2_ARADDR => m_axi_DATA_BUS2_ARADDR,
      m_axi_DATA_BUS2_ARLEN => m_axi_DATA_BUS2_ARLEN,
      m_axi_DATA_BUS2_ARSIZE => m_axi_DATA_BUS2_ARSIZE,
      m_axi_DATA_BUS2_ARBURST => m_axi_DATA_BUS2_ARBURST,
      m_axi_DATA_BUS2_ARLOCK => m_axi_DATA_BUS2_ARLOCK,
      m_axi_DATA_BUS2_ARREGION => m_axi_DATA_BUS2_ARREGION,
      m_axi_DATA_BUS2_ARCACHE => m_axi_DATA_BUS2_ARCACHE,
      m_axi_DATA_BUS2_ARPROT => m_axi_DATA_BUS2_ARPROT,
      m_axi_DATA_BUS2_ARQOS => m_axi_DATA_BUS2_ARQOS,
      m_axi_DATA_BUS2_ARVALID => m_axi_DATA_BUS2_ARVALID,
      m_axi_DATA_BUS2_ARREADY => m_axi_DATA_BUS2_ARREADY,
      m_axi_DATA_BUS2_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS2_RDATA => m_axi_DATA_BUS2_RDATA,
      m_axi_DATA_BUS2_RRESP => m_axi_DATA_BUS2_RRESP,
      m_axi_DATA_BUS2_RLAST => m_axi_DATA_BUS2_RLAST,
      m_axi_DATA_BUS2_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS2_RVALID => m_axi_DATA_BUS2_RVALID,
      m_axi_DATA_BUS2_RREADY => m_axi_DATA_BUS2_RREADY,
      m_axi_DATA_BUS3_AWADDR => m_axi_DATA_BUS3_AWADDR,
      m_axi_DATA_BUS3_AWLEN => m_axi_DATA_BUS3_AWLEN,
      m_axi_DATA_BUS3_AWSIZE => m_axi_DATA_BUS3_AWSIZE,
      m_axi_DATA_BUS3_AWBURST => m_axi_DATA_BUS3_AWBURST,
      m_axi_DATA_BUS3_AWLOCK => m_axi_DATA_BUS3_AWLOCK,
      m_axi_DATA_BUS3_AWREGION => m_axi_DATA_BUS3_AWREGION,
      m_axi_DATA_BUS3_AWCACHE => m_axi_DATA_BUS3_AWCACHE,
      m_axi_DATA_BUS3_AWPROT => m_axi_DATA_BUS3_AWPROT,
      m_axi_DATA_BUS3_AWQOS => m_axi_DATA_BUS3_AWQOS,
      m_axi_DATA_BUS3_AWVALID => m_axi_DATA_BUS3_AWVALID,
      m_axi_DATA_BUS3_AWREADY => m_axi_DATA_BUS3_AWREADY,
      m_axi_DATA_BUS3_WDATA => m_axi_DATA_BUS3_WDATA,
      m_axi_DATA_BUS3_WSTRB => m_axi_DATA_BUS3_WSTRB,
      m_axi_DATA_BUS3_WLAST => m_axi_DATA_BUS3_WLAST,
      m_axi_DATA_BUS3_WVALID => m_axi_DATA_BUS3_WVALID,
      m_axi_DATA_BUS3_WREADY => m_axi_DATA_BUS3_WREADY,
      m_axi_DATA_BUS3_BID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS3_BRESP => m_axi_DATA_BUS3_BRESP,
      m_axi_DATA_BUS3_BUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS3_BVALID => m_axi_DATA_BUS3_BVALID,
      m_axi_DATA_BUS3_BREADY => m_axi_DATA_BUS3_BREADY,
      m_axi_DATA_BUS3_ARADDR => m_axi_DATA_BUS3_ARADDR,
      m_axi_DATA_BUS3_ARLEN => m_axi_DATA_BUS3_ARLEN,
      m_axi_DATA_BUS3_ARSIZE => m_axi_DATA_BUS3_ARSIZE,
      m_axi_DATA_BUS3_ARBURST => m_axi_DATA_BUS3_ARBURST,
      m_axi_DATA_BUS3_ARLOCK => m_axi_DATA_BUS3_ARLOCK,
      m_axi_DATA_BUS3_ARREGION => m_axi_DATA_BUS3_ARREGION,
      m_axi_DATA_BUS3_ARCACHE => m_axi_DATA_BUS3_ARCACHE,
      m_axi_DATA_BUS3_ARPROT => m_axi_DATA_BUS3_ARPROT,
      m_axi_DATA_BUS3_ARQOS => m_axi_DATA_BUS3_ARQOS,
      m_axi_DATA_BUS3_ARVALID => m_axi_DATA_BUS3_ARVALID,
      m_axi_DATA_BUS3_ARREADY => m_axi_DATA_BUS3_ARREADY,
      m_axi_DATA_BUS3_RID => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS3_RDATA => m_axi_DATA_BUS3_RDATA,
      m_axi_DATA_BUS3_RRESP => m_axi_DATA_BUS3_RRESP,
      m_axi_DATA_BUS3_RLAST => m_axi_DATA_BUS3_RLAST,
      m_axi_DATA_BUS3_RUSER => STD_LOGIC_VECTOR(TO_UNSIGNED(0, 1)),
      m_axi_DATA_BUS3_RVALID => m_axi_DATA_BUS3_RVALID,
      m_axi_DATA_BUS3_RREADY => m_axi_DATA_BUS3_RREADY
    );
END design_1_IC_codec_0_16_arch;
